title: Ram J Bishnoi, MD MBA
theme: jekyll-theme-minimal
description: Bookmark this to keep an eye on my project updates!

author: "Ram J Bishnoi"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
mathjax: true
show_excerpts: false
show_frame: true



remote_theme: rjbishnoi/contrast

plugins:
 - jekyll-feed
